[package]
name = "does-it-json"
version = "0.0.1"
authors = ["Adam H. Leventhal <ahl@oxide.computer>"]
edition = "2021"
license = "Apache-2.0"
description = "Compare serde serialization with the schemars JSON schema"
repository = "https://github.com/ahl/does-it-json"
readme = "README.md"

[dependencies]
regex = "1.5.5"
schemars = "0.8.10"
serde = "1.0.137"
serde_json = "1.0.81"
thiserror = "1.0.31"

[dev-dependencies]
expectorate = "1.0.5"
